spring:
  application:
    name: order-service
  jackson:
    time-zone: "Asia/Almaty"

  datasource:
    url: jdbc:postgresql://localhost:5432/techshop-db?serverTimezone=Asia/Almaty
    username: admin
    password: 123456

  jpa:
    properties:
      hibernate:
        default_schema: order_service
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR

server:
  port: 8080

techshop:
  services:
    catalog:
      url: ${CATALOG_SERVICE_URL:"http://localhost:8082/}"
    order:
      username: ${ORDER_SERVICE_USER:"order_service_user"}
      password: ${ORDER_SERVICE_PASSWORD:"123456"}
    user:
      url: "${USER_SERVICE_URL:http://localhost:8081/}"
    kafka:
      url: ${KAFKA_URL:"localhost:9092"}
